# Generated by Django 2.1.3 on 2020-05-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='tz',
            field=models.CharField(default='Asia/Kolkata', max_length=200),
        ),
    ]
